
services:
  go-genai:
    build:
      context: ./go-genai
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  python-genai:
    build:
      context: ./py-genai
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - PORT=9090
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  node-genai:
    build:
      context: ./node-genai
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      - PORT=7070
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"